name: Continuous Integration
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # Build and test the project
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.8", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}, os: ${{ matrix.os }}, python: ${{ matrix.python }}"
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      # Using fixed Poetry version until
      # https://github.com/python-poetry/poetry/pull/7694 is fixed
      - run: python -m pip install --upgrade wheel "poetry==1.4.0" poethepoet
      - run: poetry install --with pydantic --with dsl
      - run: poe lint
      - run: poe test -s -o log_cli_level=DEBUG
      - run: poe test -s -o log_cli_level=DEBUG --workflow-environment time-skipping

      # On latest, run gevent test
      - name: Gevent test
        if: ${{ matrix.python == '3.12' }}
        run: |
          poetry install --with gevent
          poetry run python gevent_async/test/run_combined.py


